- hosts: master
  become: true
  roles:
    - oracle-java
    - init
    - ansible-jboss
    - master
    - driver
    - drivermaster
- hosts: slave
  become: true
  roles:
    - oracle-java
    - init
    - ansible-jboss
    - slave
    - driver
