- name: Installazione driver oracle
  command: /opt/jboss-eap-7.1/bin/jboss-cli.sh --command="module add --name=oracle.jdbc --resources=/opt/jboss-eap-7.1/ojdbc8.jar --dependencies=javax.api,javax.transaction.api"
