- name: Configurazione host-master.xml
  template:
    src: host-master.file
    dest: /opt/jboss-as-7.1.1.Final/domain/configuration/host-master.xml
    owner: jboss
    group: jboss
- replace:
    path: /opt/jboss-as-7.1.1.Final/domain/configuration/host-master.xml
    regexp: "IPMASTER"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
#Host config
- name: Configurazione host.xml
  template:
    src: host.file
    dest: /opt/jboss-as-7.1.1.Final/domain/configuration/host.xml
    owner: jboss
    group: jboss
- replace:
    path: /opt/jboss-as-7.1.1.Final/domain/configuration/host.xml
    regexp: "IPMASTER"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
#widlfly.conf
- name: jboss config
  template:
    src: jboss-master.conf
    dest: /etc/default/jboss-eap
    owner: jboss
    group: jboss
#jboss.service
- name: jboss service
  template:
    src: jboss.service
    dest: /etc/systemd/system/jboss-as-domain.service
    owner: jboss
    group: jboss
- name: reload daemon systemctl
  systemd: daemon_reload=yes
